---
abstract: 'Parse apache SSI directives in your CGI scripts'
author:
  - 'insaner <apacheSSI-PLEASE-NOSPAM@insaner.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-apacheSSI
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.93
